### ISSUE TITLE
Fails to build on mac, workaround

### ISSUE THREAD

**Issue by dimaqq** [quora/asynq#96]
Python 3.9.0b1, official macOS build, fresh virtualenv, `pip install asynq`  fails:

```
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/mb/xx/T/pip-install-ki69lzou/asynq/setup.py", line 57, in <module>
        setup(
      File "/v/lib/python3.9/site-packages/setuptools/__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "/v/lib/python3.9/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/v/lib/python3.9/site-packages/setuptools/dist.py", line 716, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "/v/lib/python3.9/site-packages/pkg_resources/__init__.py", line 780, in resolve
        dist = best[req.key] = env.best_match(
      File "/v/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "/v/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1077, in obtain
        return installer(requirement)
      File "/v/lib/python3.9/site-packages/setuptools/dist.py", line 786, in fetch_build_egg
        return cmd.easy_install(req)
      File "/v/lib/python3.9/site-packages/setuptools/command/easy_install.py", line 679, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/v/lib/python3.9/site-packages/setuptools/command/easy_install.py", line 705, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/v/lib/python3.9/site-packages/setuptools/command/easy_install.py", line 890, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/v/lib/python3.9/site-packages/setuptools/command/easy_install.py", line 1158, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/v/lib/python3.9/site-packages/setuptools/command/easy_install.py", line 1146, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error: command '/usr/bin/gcc' failed with exit code 1
```

I guess it should be calling something other than `gcc` on mac.
Tested with `pip==19.2.3` and `pip==20.1.1`.

However, manually installing dependencies and then `asynq` works:
```sh
(v) ~ > pip install cython
...
Successfully installed cython-0.29.19

(v) ~ > pip install qcore
Collecting qcore
...
Requirement already satisfied: Cython in... (from qcore) (0.29.19)
Collecting inspect2 (from qcore)
...
Installing collected packages: inspect2, six, qcore
  Running setup.py install for qcore ... done
Successfully installed inspect2-0.1.2 qcore-1.6.1 six-1.15.0

(v) ~ > pip install asynq
Collecting asynq
...
  Running setup.py install for asynq ... done
Successfully installed asynq-1.3.0 pygments-2.6.1
```

**Comment by JelleZijlstra** [comment]
I can reproduce this. Interestingly, it fails while building qcore, but just running `pip install qcore` works fine.

Maybe the qcore headers should be changed to use relative imports, because it also warns:
```
    /private/var/folders/75/kbphyp697t5fzgzkth6s7x380000gn/T/easy_install-4_kiv1by/qcore-1.6.1/.eggs/Cython-3.0a5-py3.9.egg/Cython/Compiler/Main.py:344: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /private/var/folders/75/kbphyp697t5fzgzkth6s7x380000gn/T/easy_install-4_kiv1by/qcore-1.6.1/qcore/microtime.pxd
```
And the errors are about how it's importing other pxd modules in qcore.

**Comment by tekumara** [comment]
Also experienced this with the error
```
 Error compiling Cython file:
    ------------------------------------------------------------
    ...
    # limitations under the License.
    
    import cython
    from cpython cimport bool
    
    cimport inspection
           ^
    ------------------------------------------------------------
    
    qcore/microtime.pxd:18:8: 'inspection.pxd' not found
```

**Comment by tekumara** [comment]
Running `pip install qcore` before `pip install asynq` works for me too.

**Comment by JelleZijlstra** [comment]
I can generally install asynq fine on Mac, please report if this becomes an issue again.
